[ingest]
bind_address = "0.0.0.0:8090"
max_event_bytes = 262144

[logging]
level = "info"
format = "json"

[management]
bind_address = "127.0.0.1:18090"
admin_password = "ingest4x"

[database]
url = "sqlite://db/ingest4x.db?mode=rwc"
refresh_interval_secs = 3

[events.sink.kafka_valid]
type = "kafka"
bootstrap_servers = "127.0.0.1:9092"
topic = "ingest4x-events"
queue_buffering_max_ms = "0"
delivery_timeout_ms = "3000"
batch_num_messages = "100"
queue_buffering_max_messages = "300"
linger_ms = "100"

[events.sink.kafka_invalid]
type = "kafka"
bootstrap_servers = "127.0.0.1:9092"
topic = "ingest4x-events-error"
queue_buffering_max_ms = "0"
delivery_timeout_ms = "3000"
batch_num_messages = "100"
queue_buffering_max_messages = "300"
linger_ms = "100"

[[events.valid.routes]]
sinks = ["kafka_valid"]
ack = ["kafka_valid"]

[[events.invalid.routes]]
sinks = ["kafka_invalid"]
ack = ["kafka_invalid"]
