[logging]
level = "info"
format = "json"

[ingest]
bind_address = "0.0.0.0:8090"
max_event_bytes = 262144

[management]
bind_address = "0.0.0.0:18090"
admin_password = "ingest4x"

[database]
url = "sqlite://db/ingest4x.db?mode=rwc"
refresh_interval_secs = 3

[wal]
dir = "./wal"
flush_max_interval = "10ms"
flush_max_records = 1000
no_sync = false
wal_segment_max_bytes = 134217728

[wal.checkpoint]
flush_interval = "1s"
flush_records = 1000
flush_bytes = 67108864

[events.sink.events]
type = "stdout"

[events.sink.events_error]
type = "stdout"
