title: ingest4x
description: Configurable, observable, and resilient event ingestion service
theme: jekyll-theme-cayman
markdown: kramdown

defaults:
  - scope:
      path: ""
    values:
      layout: default
